./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_HHggbb.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ggH.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_qqH.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_VH.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttH.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_bbH.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_gg.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttgg.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttghad.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttgsemilepfromt.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttgsemilepfromtbar.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_ttglep.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_tt.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_gjet.txt
./bin/countEvents.exe /afs/cern.ch/user/a/abenagli/public/HHGGBBAnalysis/fileList_qcd.txt
